### ISSUE TITLE
Cannot generate bug report

### ISSUE THREAD

**Issue by solofoA45** [Xpra-org/xpra-html5#236] opened 2023-03-28 10:14 UTC
xpra-html5-5.1-1.r3 Google Chrome Version 111.0.5563.64

When trying to generate a bug report, no .zip is created and errors appear in the console (see screenshot).
This is not systematic: it seems .zip is generated when no reverse proxy is used.

![Cannot-Generate-Bug-Report2](https://user-images.githubusercontent.com/126672700/228204201-137fd257-00d4-4c3d-afb4-4dc0261c9ffc.png)

**Comment by solofoA45** [comment] 2023-03-28 10:37
Also this seems browser-specific:

- KO with Google Chrome Version 111.0.5563.64 (Official Build) (64-bit)
- OK with Firefox 111.0.1 (64-bit)

**Comment by totaam** [comment] 2023-03-28 14:37
This is caused by the offscreen decode worker, which is disabled on Firefox:
https://github.com/Xpra-org/xpra-html5/blob/d08f98ce20778a1dcedf26d8c003967c631b5269/html5/js/OffscreenDecodeWorkerHelper.js#L16-L17

That's because we can't call draw on a window which is decoded offscreen.
The commit above skips the screenshot when the offscreen api is in use.

Ideally, we need a better fix so we can still get screenshots - perhaps we could add a "snapshot" call to the offscreen worker (ie: converting the canvas to a png with `canvas.toDataURL('image/png')`) but the real difficulty is that the bug report function then needs to wait for the response and that's hard to implement, it may also break the download function since this delays means that the download will no longer be a response to a user event.
For the time being, it may just be easier to offer the option to turn off the offscreen decode worker.

**Comment by totaam** [comment] 2024-07-03 10:13
I don't have the time to make the "screenshot" work with the offscreen API and since the original bug is fixed, I am closing this issue.

**Closed by totaam** 2024-07-03 10:13 UTC
