### ISSUE TITLE
Can not connect to xpra proxy server using xpra-html5

### ISSUE THREAD

**Issue by Vssblt** [Xpra-org/xpra-html5#125] opened 2021-12-16 08:24 UTC
# Can not connect to xpra proxy server using xpra-html5

## What happend
I can use command line `xpra attach tcp://XXXuser@10.68.150.111:12008/1024` to connect proxy server correctly, but not working in xpra-html5.

html5 connect.html output:
```
You were disconnected for the following reason:

server shutdown
server connection lost
```

Firefox and Chrome console output:
```
Array(3) [ "gibberish", "invalid packet header byte: 0x646973636f6e6e65 read buffer=b\"disconnect: invalid packet header byte: 0x0100 .. \\\\x94encoding.proxy.videoD\\\\x7f' (6798 bytes)\\n\" (185 bytes)", "disconnect: invalid packet header byte: 0x01000000001a87c2 read buffer=b'\\x01\\x00\\x00\\x00\\x00\\x1a\\x87\\xc2\\x85hello<\\x87 .. \\x03\\xe8\\x85proxyC\\x94encoding.proxy.videoD\\x7f' (6798 bytes)\n" ]
Utilities.js:62:16
```

## Env
OS: nvidia/cudagl-11.2.0 ubuntu in docker  

Nvidia driver version: nvidia-driver-460   

GPU: RTX3090  

## Other information
```
$ xpra --version
xpra v4.2.3-r12

$ cd /usr/share/xpra/www/ && grep "Version 4" ./index.html -r
<h3>Version 4.5.2</h3>
```

#### Xpra config file
```
$ cat /etc/xpra/xpra.conf
tcp-auth=allow
bandwidth-limit=3000Mbps
opengl=no
speaker=off
encoding=jpeg
notifications=no
system-tray=no
webcam=no
mousewheel=on
min-speed=100
min-quality=88
auto-refresh-delay=0
title="xxxxxxxxx"
mdns=no
exit-with-children=yes
video-scaling=off
exec-wrapper=/opt/VirtualGL/bin/vglrun -d :5 --
env=XPRA_CLOSE_GTK_DISPLAY=0 XDG_RUNTIME_DIR=/xxx/runtime/xdg-start
sharing=yes
server-idle-timeout=30
idle-timeout=10800
terminate-children=yes
dbus-launch=no
bandwidth-detection=no
file-size-limit=10000M
clipboard=default
printing=no
socket-dirs=/xxx/runtime/xpra/socket
```

#### Xpra proxy config file
```
$ cat /etc/xpra/xpra_proxy.conf
socket-dirs=/xxx/runtime/xpra/socket
```

#### Env
```
$ cat /etc/profile
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda-11.2/compat/   # For nvjpeg and nvenc. 
export XDG_RUNTIME_DIR=/xxx/runtime/xdg-start
```

#### Xpra command line:
```
$ su - XXXuser -c "XPRA_CONF_FILENAME=/etc/xpra/xpra_proxy.conf /usr/bin/xpra proxy :20 --socket-dirs=/xxx/runtime/xpra/socket --daemon=yes --bind-tcp=0.0.0.0:12008 --tcp-auth=allow 2>&1 > /dev/null &"

$ /usr/bin/python3 /usr/bin/xpra start :1024 --tcp-auth=password:value=1 --daemon=no --start-child=/xxx/app/app --exit-with-children
```

**Comment by Vssblt** [comment] 2021-12-16 08:32
I want to use nvjpeg and nvenc, so I upgraded xpra to 4.2.3, xpra-html5 to 4.5.2 and installed cuda.
It does work without proxy, but doesn't work in proxy mode anymore. 
I am sure nvjpeg was running correctly without proxy, all debug info is fine. `-d nvjpeg`

**Comment by totaam** [comment] 2021-12-16 08:57
Probably a duplicate of https://github.com/Xpra-org/xpra/issues/3349

Please try with 4.3 which was released 5 minutes ago.

**Comment by Vssblt** [comment] 2021-12-17 03:29
Thanks for your reply. I upgrade to xpra-4.3 everything is working fine.

**Closed** 2021-12-17 03:29 UTC
