### ISSUE TITLE
webrtc protocol

### ISSUE THREAD

**Issue by tardyp** [Xpra-org/xpra-html5#165] opened 2022-03-24 12:24 UTC
google's cuttlefish android emulator uses webrtc force  streaming the real time video.
https://android.googlesource.com/device/google/cuttlefish/+/refs/heads/master/host/frontend/webrtc/client/

webrtc looks like more appropriate than the other alternatives implemented here and discussed in this repo's issue.

I wonder if there is any blocker that you have foreseen that I couldn't see.

**Comment by totaam** [comment] 2022-03-24 13:51
Duplicate of #28

In particular, see https://github.com/Xpra-org/xpra-html5/issues/28#issuecomment-820531238

**Closed by totaam** 2022-03-24 13:51 UTC
