### ISSUE TITLE
New windows sometimes not on top

### ISSUE THREAD

**Issue by Rush-iam** [Xpra-org/xpra-html5#239] opened 2023-04-10 20:28 UTC
When you launch a new program within the client, having a different window opened, the new one doesn't always get focused (doesn't go on top).

When some app opens an internal window (subwindow), the client may reshuffle window order  - the background window may become on top (or not on top but in the middle of three windows and return to the background after closing the top window).

**Comment by totaam** [comment] 2023-04-11 04:54
Yes, window stacking should be completely re-written.
Unfortunately, I don't have time to dedicate to that.

**Comment by totaam** [comment] 2024-07-03 10:31
Duplicate of #11

**Closed by totaam** 2024-07-03 10:31 UTC
Labels: bug
