### ISSUE TITLE
Implementing QUICK and UDP transport

### ISSUE THREAD

**Issue by dexion** [Xpra-org/xpra-html5#275] opened 2023-12-27 14:13 UTC
Hi! Do you have plans to implement QUICK and UDP transport for html client? This functionality is already implemented in a fat-client.

**Comment by totaam** [comment] 2023-12-27 17:32
The server does support QUIC: #3376 but what the html5 client actually needs is [WebTransport](https://developer.mozilla.org/en-US/docs/Web/API/WebTransport), the server stub here is incomplete: https://github.com/Xpra-org/xpra/blob/master/xpra/net/quic/webtransport.py

This ticket is a duplicate of #143

**Closed by totaam** 2023-12-27 17:32 UTC
