### ISSUE TITLE
Window position offset

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra-html5#88] opened 2021-08-02 16:50 UTC
Not sure if this is related to xpra or the client, but I noticed that the popup window's position is shifted up by the height of the title bar.

In native macOS, when I type something in the search bar in the Fiji software, a window will show below attached exactly to the main window:
<img width="805" alt="Screen Shot 2021-08-02 at 6 23 30 PM" src="https://user-images.githubusercontent.com/478667/127896084-3e0bae88-7148-4468-9e69-c258b446b748.png">

However, when I do the same in Xpra, the popup window position is shifted up to cover the search bar (the offset height roughly equal to the height of the title bar):

<img width="809" alt="Screen Shot 2021-08-02 at 6 24 22 PM" src="https://user-images.githubusercontent.com/478667/127896220-479debe9-f065-41e5-a0cd-adc1c337b5cb.png">

Does this mean xpra didn't take into the account of the title bar height when displaying the window?

**Comment by totaam** [comment] 2021-08-03 03:23
Does this also occur with the xpra non-html client?

**Comment by oeway** [comment] 2021-08-03 14:12
> Does this also occur with the xpra non-html client?

Sorry, I cannot make the native client work with my server. Basically my server serves serves the ws connection under a subpath `/desktop` and it requires a token to authenticate. So the native client cannot connect to it.

**Comment by totaam** [comment] 2021-08-03 14:21
You can use an ssh tunnel, or just install it somewhere else surely?

**Comment by oeway** [comment] 2021-08-03 16:16
Sorry I don't have access to any host which I can install xpra at the moment. I tried once with a remote server with no x window but couldn't get it to work. The working version I was using is in docker based servers behind firewalls which doesn't allow ssh (only http). If possible, could you try with the App download link I posted in a previous issue? It should be rather easy to reproduce, start the app and type something in the search bar.

Otherwise, I will check if I can find another machine later this week.

**Comment by iDmple** [comment] 2021-09-08 15:18
I have the same issue. Could you please take a look?
<img width="683" alt="Screenshot 2021-08-25 at 09 14 14 (1)" src="https://user-images.githubusercontent.com/5065505/132537216-53f6d8d7-1d26-4608-b4bc-3b11189112e4.png">

**Comment by iDmple** [comment] 2021-09-13 09:14
I just got the 4.4 update and it seems to be fixed?

**Comment by totaam** [comment] 2021-09-14 13:22
It's not clear to me which version @iDmple and @oeway were using previously.

> I just got the 4.4 update and it seems to be fixed?

I'm going to close this. Please re-open with more details if you can still reproduce the bug.

**Closed by totaam** 2021-09-14 13:22 UTC
Labels: bug, question, geometry

**Comment by iDmple** [comment] 2021-09-14 13:59
It was the previous ubuntu package release. The one that had the remaining on screen keyboard bug. In that thread I mentioned the exact version, sorry can't look now.Thanks for fixing!!!15:23, September 14, 2021, Antoine Martin ***@***.***>:
It's not clear to me which version @iDmple and @oeway were using previously.

I just got the 4.4 update and it seems to be fixed?

I'm going to close this. Please re-open with more details if you can still reproduce the bug.

**Comment by iDmple** [comment] 2021-09-14 14:01
Ubuntu 20.0415:59, September 14, 2021, Nathalie Casati ***@***.***>:It was the previous ubuntu package release. The one that had the remaining on screen keyboard bug. In that thread I mentioned the exact version, sorry can't look now.Thanks for fixing!!!15:23, September 14, 2021, Antoine Martin ***@***.***>:
It's not clear to me which version @iDmple and @oeway were using previously.

I just got the 4.4 update and it seems to be fixed?

I'm going to close this. Please re-open with more details if you can still reproduce the bug.
